Repository syssrc/21-ip-assignment, pull requests merged in 2021-11, with the labels that each got.

#16 1068
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#10 feat(conditional/Cashier): add 'java.util.Scanner' object
  loop/src/main/java/ip/syssrc/loop/Eyes.java
  loop/src/main/java/ip/syssrc/loop/FactorialSequence.java
  loop/src/main/java/ip/syssrc/loop/MatricesPad.java
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
Labels: help wanted

#18 1064
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#15 1069
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#8 1085
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#28 1044
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#12 feat(conditional/cashier): add 'java.util.Scanner' object
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#30 1053
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#2 assignment 1.1
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#17 1058
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#36 1001
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#19 H071211071 Tugas 1 & 2
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#35 1079-Tugas Praktikum
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#27 1056 - Tugas Praktikum 1 & 2
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#29 1076
  src/main/java/ip/syssrc/App.java
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#25 1072
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#22 1078 - Tugas Praktikum 1 dan 2
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#13 1065
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/loop/FactorialSequence.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: help wanted

#43 Assigment 3-1056
  src/main/java/ip/syssrc/array/CountEach.java
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/array/SumOneThird.java
  src/main/java/ip/syssrc/conditional/CashierSolution.java
  src/main/java/ip/syssrc/conditional/RoleAccessSolution.java
Labels: help wanted

#77 Assignment 3 - 1072
  src/main/java/ip/syssrc/array/CountEach.java
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/array/SumOneThird.java
Labels: Late

#70 Assignment 3 - 1065
  src/main/java/ip/syssrc/App.java
  src/main/java/ip/syssrc/array/CountEach.java
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/array/SumOneThird.java
  src/main/java/ip/syssrc/conditional/CashierSolution.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/conditional/RoleAccessSolution.java
Labels: bug, help wanted

#47 Assignment 3 - 1087
  src/main/java/ip/syssrc/array/CountEach.java
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/array/SumOneThird.java
  src/main/java/ip/syssrc/conditional/CashierSolution.java
  src/main/java/ip/syssrc/conditional/RoleAccessSolution.java
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
Labels: help wanted, invalid

#108 Assignment 4 - 1056
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
Labels: Late

#111 Assignment 3 - 1001
  src/main/java/ip/syssrc/array/CountEach.java
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/array/SumOneThird.java
Labels: Late

#95 Assignment 4 - 1080
  src/main/java/ip/syssrc/array/RadixConverter.java
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
Labels: HELP WANTED, INVALID!

#96 Assignment 4 - 1085
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
  src/main/java/ip/syssrc/loop/MatricesPad.java
Labels: HELP WANTED, INVALID!

#107 Assignment 4 - 1087
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
Labels: Late

#144 Assignment 4 - 1001
  src/main/java/ip/syssrc/conditional/CashierSolution.java
  src/main/java/ip/syssrc/conditional/RoleAccessSolution.java
  src/main/java/ip/syssrc/function/BigInt.java
  src/main/java/ip/syssrc/function/Vigesimal.java
  src/main/java/ip/syssrc/string/FizzBuzz.java
  src/main/java/ip/syssrc/string/URLParser.java
  src/main/java/ip/syssrc/string/Vocab.java
Labels: Late

#148 Assignment 5 - 1065
  src/main/java/ip/syssrc/collection/DataManipulation.java
  src/main/java/ip/syssrc/collection/TemplateParse.java
  src/main/java/ip/syssrc/conditional/Cashier.java
  src/main/java/ip/syssrc/conditional/RoleAccess.java
  src/main/java/ip/syssrc/loop/Eyes.java
  src/main/java/ip/syssrc/string/FizzBuzz.java
  src/main/java/ip/syssrc/string/URLParser.java
  src/main/java/ip/syssrc/string/Vocab.java
Labels: Late
